title: rk language
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
search_enabled: false
url: https://rklang.dev

footer_content: "&copy; 2020 Sergii Iefremov. Code licensed under MIT license."

markdown: kramdown
highlighter: rouge
