remote_theme: pmarsceill/just-the-docs
search_enabled: false
footer_content: "&copy; 2020 Sergii Iefremov. Code licensed under MIT license."
aux_links:
  "GitHub<span class=\"label label-yellow\">COMING SOON</span>":
    - "/about"

title: Molten C
tagline: Molten C
description: Modern low-level non-object-oriented programming language based on C
url: https://moltenc.dev
author: iefserge
logo: https://moltenc.dev/logo.png
image:
  path: /logo.png
  height: 256
  width: 256

markdown: kramdown
highlighter: rouge

ga_tracking: UA-159983849-1
twitter_text: "Molten C – yet another “systems” programming language"

sass:
  sass_dir: _sass
  style: compressed

twitter:
  username: iefserge
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://moltenc.dev/logo.png

plugins:
  - jekyll-seo-tag
  - jekyll-titles-from-headings
  - jekyll-remote-theme
